### ISSUE TITLE
Make 'title' field single-value

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#39] opened 2015-07-20 18:32 UTC

**Comment by hackmastera** [comment] 2015-07-20 20:18
duplicate of #16

**Comment by hackmastera** [comment] 2015-09-18 15:38
actually not a duplicate; it's better to keep these separate; reopening.

**Comment by MDiMeo** [comment] 2015-09-18 16:16
Just talked with @catlu. She doesn't feel strongly about this and decided it's actually ok to leave it as a repeatable field. She mentioned that it's addressed in the metadata guidelines and that it could actually be interesting to see how people repeat it if they try to. I'll wait for her to weigh in, but I think we can close this issue.

**Comment by hackmastera** [comment] 2015-09-18 16:20
One thing to consider is that it's much easier to move from single valued to multivalued than vice-versa.

If y'all do see value in having it single value, it might be worth having another look at this to see if it looks any easier to fix than it did in July.

**Comment by hackmastera** [comment] 2015-10-05 16:21
Okay revisiting this one last time! I believe I can fix this quite easily as a frontend-only fix. So please let me know from your heart of hearts whether you truly prefer a single- or multi-valued field for title. Thanks!

**Comment by catlu** [comment] 2015-10-05 19:03
Let's stick with multi-valued for now.

**Closed** 2015-10-05 19:04 UTC
