### ISSUE TITLE
Error with batch upload to staging server

### ISSUE THREAD

**Issue by MDiMeo** [chemheritage/chf-sufia#48] opened 2015-07-30 19:44 UTC
I tried uploading a folder of Tiff and Jpeg images. I received the error "All files selected from .DS_Store and after will not be uploaded because your total upload is too big. You may not upload more than 500 MB in one upload." I deleted the .DS_Store since it said it was an unsupported file type, then tried uploading all 50+ files. It runs 6 uploads at a time. I had a series of successful uploads, then it just stopped working and I got all Error statuses even though it looked like files were uploading. It may have stopped working after it reached 500 MB for this batch, or it may be that uploading the 180 MB TIFF  crashed the system because this took a VERY long time. The 45 MB Jpegs were perfectly fine.

**Comment by hackmastera** [comment] 2015-07-30 19:59
@MDiMeo what / where /when did you see the message that .DS_Store is unsupported?

**Comment by MDiMeo** [comment] 2015-07-31 12:52
@hackmastera When I attached the folder and all the files started populating the Upload screen, "Error: Filetype Not Allowed" showed up instead of the progress bar where it would show a download in progress (the space between the file size and the Cancel button). Interestingly, I can't seem to find the .DS_Store file in the folder itself when I'm not in Sufia, which is M:RareBooks/Pilot.

**Comment by hackmastera** [comment] 2015-07-31 13:16
Got it, thanks. That seems like a reasonable way for Sufia to handle .DS_Store - skip it and tell you why. Yeah, the .DS_Store file doesn't normally show up when you browse the files in the OS / Finder. The leading dot is an indicator of an invisible file. I think you can have the finder show invisible files but I don't know how off the top of my head. There is also a way to see them via terminal (command-line).

**Comment by hackmastera** [comment] 2015-08-07 15:52
We replicated the problem and jetty crashed again. We tried a few variations. Ultimately we got some useful information when uploading 10 ~42mb files. 2 or 3 succeeded, then 4 failed, then the rest succeeded. Here's the apache log from that upload:

[ 2015-08-07 15:39:44.8613 29380/7f79e62d8700 age/Hel/Main.cpp:794 ]: Disconnecting long-running connections for process 29831, application /opt/sufia-project/current
[ 2015-08-07 15:42:08.9655 29380/7f79e62d8700 age/Hel/Main.cpp:794 ]: Disconnecting long-running connections for process 29500, application /opt/sufia-project/current
[ 2015-08-07 15:42:08.9658 29380/7f79e62d8700 age/Hel/Main.cpp:794 ]: Disconnecting long-running connections for process 29520, application /opt/sufia-project/current
App 30502 stdout: 
[ 2015-08-07 15:43:47.4088 29380/7f79e034f700 App/Implementation.cpp:303 ]: Could not spawn process for application /opt/sufia-project/current: An error occurred while starting up the preloader: it did not write a startup response in time.
  Error ID: 21f70867
  Error details saved to: /tmp/passenger-error-teCIdg.html
  Message from application: An error occurred while starting up the preloader: it did not write a startup response in time. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
(empty)

[ 2015-08-07 15:43:48.4495 29380/7f79db7fe700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 1-41] Cannot checkout session because a spawning error occurred. The identifier of the error is 21f70867. Please see earlier logs for details about the error.
[ 2015-08-07 15:43:48.4804 29380/7f79db7fe700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 1-39] Cannot checkout session because a spawning error occurred. The identifier of the error is 21f70867. Please see earlier logs for details about the error.
[ 2015-08-07 15:43:48.4854 29380/7f79db7fe700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 1-40] Cannot checkout session because a spawning error occurred. The identifier of the error is 21f70867. Please see earlier logs for details about the error.
[ 2015-08-07 15:43:48.4895 29380/7f79db7fe700 age/Hel/Req/CheckoutSession.cpp:252 ]: [Client 1-43] Cannot checkout session because a spawning error occurred. The identifier of the error is 21f70867. Please see earlier logs for details about the error.

**Comment by hackmastera** [comment] 2015-08-07 17:40
Currently I am thinking the problem is ultimately one of resources. Perhaps we need more memory or more CPUs. I was able to see CPU usage on the aws monitoring dashboard; I wasn't able to see memory usage there. The CPU usage spiked at/near 100% (please note that as far as I understand this isn't necessarily a bad thing -- you should be able to use all your CPUs). 

I read the url given about startup in the log - https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems - and I think our issue is probably due to the last option on that page. The reason I don't think it's any of the others because we don't get this problem at any other time except during this resource-intensive upload.

Also the fact that we have observed problems not just with passenger but also with tomcat crashing leads me to believe the problem is outside of any service or application and is just due to resource load.

I will look into current memory and CPU capacity and update this issue.

We can also look to mitigate the problem by decreasing maximums in Sufia (e.g. the number of files that can upload at once, since we had success uploading 4 files simultaneously) and/or increasing timeouts in passenger/apache, such as maybe
* https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerPoolIdleTime
* https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerMaxRequestTime can't be changed and appears to default to no limit but perhaps there is a similar setting in apache itself.

**Comment by hackmastera** [comment] 2015-08-07 17:51
We're currently running m3.medium, which has the following stats:
m3.medium	1CPU	3.75GiB memory	1 x 4 GB

I think we should definitely step up to m3.large (2CPU, 7.5 GiB memory) and consider m3.xlarge (4CPU, 15 GiB memory).

@MDiMeo Do you want to look into the cost implications? We can continue this conversation on basecamp (I'll copy this info there).

**Comment by MDiMeo** [comment] 2015-08-12 14:36
@hackmastera Yes, I will look into the m3.large upgrade and get back to you. Thanks for this.

**Comment by hackmastera** [comment] 2015-08-28 18:47
I haven't had an error report in a while. I'll consider this resolved with the VM migration; we'll see how things go with a larger set of testers.

**Closed by hackmastera** 2015-08-28 18:47 UTC
