### ISSUE TITLE
Production - Problems with multi-page work 

### ISSUE THREAD

**Issue by catlu** [chemheritage/chf-sufia#896] opened 2017-11-07 14:46 UTC
[Work ID: ff365590j] I noticed these two issues after I went to delete 4 files from the work (my guess is the work might've still been processing other files).

1) File manager not working properly--when I go into File Manager and hit Sort Alphabetically > Save, usually the Save button grays out after saving successfully. This one goes into a loop that allows you to click the Save button over and over again, but when you go back to the main work page, the files haven't been successfully sorted.

2) Unable to add child works successfully--when I input a title of a child work, a message that says "loading failed" pops up. There are 4 previous child works that were added when the work wasn't broken yet.

![work2](https://user-images.githubusercontent.com/11876037/32499219-fbea38a8-c39f-11e7-87d8-d983dd4a97fc.png)

**Comment by jrochkind** [comment] 2017-11-20 22:59
@catlu hey, can you remind me how I get to the 'file manager' to try 'sort alphabetically' to see if I can reproduce?

And it's okay if I save this one sorted alphabetically in production?

**Comment by catlu** [comment] 2017-11-20 23:05
@jrochkind the 'file manager' button is next to the edit button on the show page. Yep, feel free to sort alphabetically.

**Comment by jrochkind** [comment] 2017-11-21 14:59
Thanks for the good error report @catlu. Have reproduced in production on trying to re-sort and save. 

Tried reindexing the work and all it's members to see if that resolved it. Sadly, it did not. Will have to  try to debug on production, which is always painful, since I have not yet reproduced in dev. Or I'll try harder to repro in dev.

**Comment by jrochkind** [comment] 2017-11-21 15:46
@catlu ok, the data had gotten corrupted somehow. It's beyond me to explain how/why/when. 

I seem to have fixed it. I can't quite explain how either, but it involved `w.ordered_members = w.members` (somehow the `members` and `ordered_members` lists had gotten out of sync, with disastrous consequences). I have sorted members alphabetically now without error. 

I am _pretty sure_ I didn't lose any data, like dropping a page that used to be there. I tried my best to be sure I didn't do that. But if you have a way to check and make sure all the pages you expect are there, it would be good -- but I'm not sure if there's a non-crazy way for you to do that. 

I haven't checked the "Unable to add child works successfully" problem, because I'm not sure how to get to that screen. But I suspect it will be fixed too. Can you try and confirm?

It still takes a long time to view or edit this many-paged work. Sufia is just... not great. 

I _think_ this work has had it's data fixed so it's no longer creating those errors now though. Can you confirm?

**Comment by catlu** [comment] 2017-11-21 16:28
No worries about losing data/pages--I'll check it at the very end since the work isn't finished yet anyway.

Unfortunately, the child works problem is still there, same behavior as before. You can navigate to the screen by going into the edit form > Relationships tab.

**Comment by jrochkind** [comment] 2017-11-21 22:12
Trying to figure it out. This one seems to not be a data corruption issue, but actually that sufia is having trouble handling that many pages. We may have hit a pretty fundamental sufia bug, sadly. this software is not good.

**Comment by jrochkind** [comment] 2017-11-21 22:31
Technical notes:

Here's the honeybadger backtrace: https://app.honeybadger.io/fault/53196/7a3efeab9b2bfa46faaa25a698d00d96

a) The app is trying to make some ungodly huge request to solr, which seems like a bad design no matter what. 

b) it's actually the "qa" questioning_authority gem, which ought not to be involved in the input field for selecting a _child work_ at all as far as I know. It's used for vocabulary completion. 

The whole thing makes no sense, I think it's a bunch of nonsense code. 

But may be able to "fix" it by telling the app to use POST instead of GET with solr, so it doesn't get the URI too long error. What the app is doing still makes no sense to me and is terrible, but it's beyond me right now to fix fundamental problems in sufia/qa.

**Comment by jrochkind** [comment] 2017-11-21 22:40
Ah, it's worse. It's not because there are so many pages in this owrk, it's because YOU, @catlu, _own_ so many works. There is a fundamental design flaw in the app where it does crazy things when you own so many works, it does not scale properly with number of works you own. 

qa is used for fetching child works for some reason, that's not a bug, that's for some reason I don't understand intended. 

I will still try changing from GET to POST... but apparently sufia does not like you owning thousands of works, @catlu, and I wouldn't be surprised if it causes you problems. We should find some way to remove you as owners from all those works or something, I dunno. Kind of at my wit's end.

**Comment by jrochkind** [comment] 2017-11-21 22:54
thought it was something else, but it really is the number of pages/child works, yep. ugh.

**Comment by jrochkind** [comment] 2017-11-22 14:38
@catlu okay, I think I've fixed it so you can use the 'add child works' option without an error. Everything is still slower than ideal with this work, but the error is gone I think. 

Can you confirm?

**Closed** 2017-11-22 15:11 UTC
