### ISSUE TITLE
Fedora Fixity errors

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#619] opened 2017-06-16 15:13 UTC
The fixity errors that @catlu ran across (and got stuck in the e-mail filter) seem to be related to this issue we saw earlier when looking at fixity:
https://jira.duraspace.org/browse/FCREPO-2433

The message @catlu got shows the incorrect URL for getting fixity checks on versions of files in Fedora.

One idea is that the alerts are still using the bad form of the URL for fixity and that's causing the error.

**Comment by hackmastera** [comment] 2017-06-16 15:25
The error would be caused if the bad URL were being stored in the db and retrieved / used without being fixed.

The start of the errors seems to coincide with this commit https://github.com/chemheritage/chf-sufia/commit/5f454fe5efc9540a922fb80eeb3a63077df18011 but I'm not really sure if that's relevant. I think / assume the fixity cron was running successfully before then.

**Comment by jrochkind** [comment] 2017-06-19 14:13
http://54.235.6.249:8080/fedora/rest/prod/zw/12/z5/65/zw12z565t/files/e24e79d8-9a81-4a2d-8d55-917ae38a2107/fcr:versions/version1/fcr:fixity

Good: http://54.235.6.249:8080//fedora/rest/prod/zw/12/z5/65/zw12z565t/files/e24e79d8-9a81-4a2d-8d55-917ae38a2107/fcr%3aversions/version1/fcr:fixity

Note the fcr:versions vs vcr%3a difference

**Comment by jrochkind** [comment] 2017-06-19 20:32
There WERE problems in the _notification messages_, which I am fixing, including the `:`=>`%3a` escaping issue. 

Those particular problems did not effect the actual check itself. 

I spot checked a few FileSet ids from the fixity failure notifications on staging. They do not fail when run again, they pass.  And staging is still running fedora 4.7.3, true?

I'm wondering if it was somehow a temporary thing, perhaps the fixity job (which takes a while) was going on _while_ the staging server was being rebuilt, and that caused it to fail. 


The actual results logged in the db as ChecksumAuditLog rows don't actually record enough info to tell us any more than we know -- something decided the thing had failed it's fixity check, and to log it as such. But why did it decide this?  Unclear not logging any context other than "It appears to have failed". 

I'm going to see if I can find any relevant Rails logs with more info....

**Comment by jrochkind** [comment] 2017-06-19 20:50
My next idea was finding Rails logs from that time period, to see if any more information on why the fixity checks might have failed could be found in logs. But I was unable to find logs from that time period, the log files seemed to have a gap.

The time period the in-app notifications say they sent the fixity failure messages (assuming that's trustworthy) are Wed, 14 Jun 2017 02:38:51 EDT -04:00   to Wed, 14 Jun 2017 02:47:35 EDT -04:00. 

It may be that there was server work going on then, which caused the fixity check to fail. 

I'm kind of out of ideas here. Not sure what caused it, or if something should be changed to avoid it happening again. 

These files won't currently be re-checked for fixity for another 7 days. When they are re-checked, I believe they will all pass. 

I am going to write a rake task to force re-check all failed checks immediately, to not have to wait the 7 days. So if this happens again because of a temporary thing, we can at least run that task to turn them all (or some of them) green again.

**Comment by jrochkind** [comment] 2017-06-19 21:32
Re-ran all failed checks on staging -- they all passed this time. 

Will soon have a rake task to do that when needed. 

This may be all we can do for now, see if any fail again.

**Comment by jrochkind** [comment] 2017-06-19 21:33
I wonder if fixity checks were running on stuff a curator just uploaded, somehow _before_ the file was actually ingested into fedora???  The FileSet object existed (so the nightly fixity check found it and wanted to check it), but the actual bytestream wasn't in fedora yet. 

@hackmastera does that seem possible?

**Comment by hackmastera** [comment] 2017-06-19 23:39
Hm, doesn't really seem possible at 2:30 am...

**Comment by jrochkind** [comment] 2017-06-20 00:05
Yeah, it doesn't really. I'm out of ideas or other places to look for evidence though. I guess we'll see if it happens again, close for now?

I do have a rake task now to immediately re-run fixity checks only on bytestreams that failed their last fixity check, so if it happens again we can immediatley re-run and see if any fail again.

**Comment by jrochkind** [comment] 2017-06-20 00:30
I think someone (sarah? cat?) did say all (many?) of these are indeed the batch they added the day before though. 

I wonder if something's going wrong in the fedora ingest such that that could be what actually happened. So many things I don't trust involved in this processing!

**Comment by hackmastera** [comment] 2017-06-20 12:58
So maybe the next step is to add a new batch to staging?

**Comment by sanfordd** [comment] 2017-06-20 19:46
Just so it's in the record, today @archivistsarah added a work with 97 files to staging as a test.

**Comment by hackmastera** [comment] 2017-06-21 12:40
Empty report from Sendio this morning. not sure what more we can do here.

**Comment by jrochkind** [comment] 2017-06-21 13:39
Checked the db on staging for ChecksumAuditLog records which register failures -- these are logged in the db like this, and while old log records are cleaned up by the fixity check process, **failure** recordings should not be. 

Comfirmed that the only failure recordings in there are from 2017-06-14 06:38:51 UTC to 2017-06-14 06:47:35 UTC. 

As far as I can tell, it was only that one batch of failures. And indeed none last night.

**Comment by jrochkind** [comment] 2017-06-21 13:41
Also confirmed that no versions are currently marked as failing, with:

     ChecksumAuditLog.latest_checks.where(passed: false).count

Ideally, we'd have an admin interface which gave you statistics on this stuff, but I didn't get to it in the fixity 'sprint'.

**Comment by hackmastera** [comment] 2017-06-21 14:38
well if we can't replicate we should close the issue.

**Closed** 2017-06-21 14:50 UTC
Labels: bug
