### ISSUE TITLE
Timeline search feature

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#329] opened 2017-02-17 19:17 UTC
a date slider or some such

**Comment by jrochkind** [comment] 2017-03-27 19:25
https://github.com/projectblacklight/blacklight_range_limit is hopefully working with the version of Blacklight and everything else we got.

**Comment by hackmastera** [comment] 2017-03-28 19:55
I'd like to talk about this one together.

**Comment by catlu** [comment] 2017-04-10 14:24
In the "my works" view, the date slider isn't there, instead it's a listing of dates:

![capture 1](https://cloud.githubusercontent.com/assets/11876037/24866330/cf963e28-1dd7-11e7-85bc-994267f8cb8c.PNG)

**Comment by jrochkind** [comment] 2017-04-10 16:35
It's astoundingly confusing to try and get this to work on My Works view. 

I don't like leaving it there, there could be thousands of unique dates, it can't be left as it is. 

If I can't get it to work in My Works view, what do you think about removing this facet from My Works view?  (Have to figure out how to do _that_ too, it's not obvious)

**Comment by jrochkind** [comment] 2017-04-10 17:26
Some notes on this feature in general and how it calculates things for 'odd' dates should be consulted at #440

**Comment by catlu** [comment] 2017-04-10 17:32
@jrochkind Either removing it or collapsing it is fine with me--I'm really not too fussed about it not working correctly in the My Works tab.

**Comment by hackmastera** [comment] 2017-04-11 13:21
@jrochkind ready to close?

**Comment by jrochkind** [comment] 2017-04-11 13:25
a timeline search feature is merged to master; there is no date facet/timeline search on 'my works' page, just public page.

**Comment by jrochkind** [comment] 2017-04-11 15:01
Weird. 

> clu [10:59 AM] 
> btw @jrochkind i noticed the date slider facet on production when i'm logged in, but it's not there when i'm logged out, is that intentional?

**Comment by catlu** [comment] 2017-04-11 15:56
another weird thing: when I facet to "unknown" in the date slider for production data, lots of stuff with specific dates show up.

**Comment by jrochkind** [comment] 2017-04-11 16:35
Weirder, I can't reproduce this in dev on my workstation, even though I saw it happening in production. 

Wait, now I can't reproduce in production either. @catlu can you still reproduce in production? Try refreshing the page?

**Comment by jrochkind** [comment] 2017-04-11 16:36
Ah, I think production needs a reindex now that the date facets are live, to get date facet values in there. Will run now, it does not require downtime and should not interfere with concurrent staff use.

**Comment by catlu** [comment] 2017-04-12 16:23
@jrochkind Can confirm things look good to me. We do have a good amount of stuff still waiting in the wings for metadata, so that's definitely related to workflow and non-public visibility, so not a bug!

**Closed** 2017-04-12 17:26 UTC
Labels: gantt: facets, gantt: timeline search, jrochkind-interested
